### ISSUE TITLE
Not being able to deploy examples

### ISSUE THREAD

**Issue by medeag** [albarivas/graphql-examples#1]
I'm getting errors when trying to push/deploy examples, could you please review?

```
 Error conferencesPanel Validation error of type FieldUndefined: Field 'Conference__c' in type 'RecordQuery' is undefined @ 'uiapi/query/Conference__c'. line: 5, column: 25, startIndex: 124 
```

**Comment by albarivas** [comment]
Hi - not sure why this happens. Commented on https://github.com/forcedotcom/cli/issues/2419. Thanks!

**Comment by albarivas** [comment]
This was a bug of the GraphQL server, and it's been solved. Thanks for reporting!
